name: deploy

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.x

permissions:
  contents: write

jobs:
  build_site:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python runtime
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up build cache
        uses: actions/cache@v3
        id: cache
        with:
          key: ${{ runner.os }}-${{ hashFiles('.cache/**') }}
          path: .cache

      - name: Install Python dependencies
        run: |
          pip install \
            "pillow<10" \
            "cairosvg>=2.5" \
            "mkdocs-material" \
            "mkdocs-material-extensions" \
            "mkdocs-git-committers-plugin-2>=1.1.1" \
            "mkdocs-git-revision-date-localized-plugin>=1.0" \
            "mkdocs-minify-plugin>=0.3" \
            "mkdocs-rss-plugin>=1.2" \
            "mkdocs-redirects>=1.0"

      - name: Deploy site
        run: |
          mkdocs --version
          mkdocs gh-deploy --force
