name: 'Security scan for stackerbuild.io'
on:
  schedule:
    - cron: '30 1 * * *'
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan (stackerbuild.io)
        uses: zaproxy/action-baseline@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://stackerbuild.io'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'